os:
  - osx

language: sh

before_install:
  - brew update

install:
  - brew install shellcheck

script:
  # TODO: Add actual assertions about expected state
  # i.e. presence of dotfiles, directories, applications.
  - shellcheck mac install-dotfiles && ./mac
  - source $HOME/.zshrc

cache:
  timeout: 900
  directories:
    - $HOME/Library/Caches/Homebrew

notifications:
  email: false
