os:
  - osx

language: sh

install:
  - brew install shellcheck

script:
  # TODO: Add actual assertions about expected state
  # i.e. presence of dotfiles, directories, applications.
  - shellcheck mac install-dotfiles
  - mac
  - echo "SUCCESS!"

notifications:
  email: false
