os:
  - osx

language: sh

before_install:
  - brew update

install:
  - brew install shellcheck

script:
  # TODO: Add actual assertions about expected state
  # i.e. presence of dotfiles, directories, applications.
  - shellcheck mac install-dotfiles && ./mac
  - aliases

notifications:
  email: false
