#!/bin/sh

# This script installs dotfiles and related tools onto your computer
# Where possible, care has been taken to make it customizable for others' needs.

DOTFILES_REPO="fauxton/dotfiles"
DOTFILES_DIR="$HOME/code/sys/dotfiles"

# Pull down dotfiles
mkdir -p "$DOTFILES_DIR"
git clone "https://github.com/$DOTFILES_REPO.git" "$DOTFILES_DIR"

# Set zsh as shell (as part of installation instructions)
chsh -s "$(which zsh)"

# Link dotfiles
env RCRC="$DOTFILES_DIR/rcrc" rcup
